---
title: "week 10"
author: "kwon"
date: "2018년 11월 1일"
output: pdf_document
---

```{r setup}
Election = seq(1952, 2004, 4)
IncumbentPct = c(44.6, 57.8, 49.9, 61.3, 49.6, 61.8, 49.0, 44.7, 59.2, 53.9, 46.5, 54.7, 50.3, 51.2)
IncomeGrowth = c(2.4, 2.9, 0.8, 4.2, 3.0, 3.6, 1.1, -0.4, 3.9, 2.3, 0.4, 1.0, 2.4, 1.9)

bp =data.frame(Election, IncumbentPct, IncomeGrowth)
```

## Classical lm
```{r}
mod = lm(IncumbentPct~IncomeGrowth, data=bp)

(X = model.matrix(mod))
betahat = coef(mod)
smod=summary(mod)
s.2 = smod$sigma^2
Vbeta = smod$cov.unscaled
n.minus.k = df.residual(mod)
```

## Posterior Simulation
```{r posterior simulation}
library(MASS)
Nsim = 1000
post.sigma.2.sim = n.minus.k*s.2/rchisq(Nsim, n.minus.k)

post.beta.sim = matrix(NA, Nsim, length(betahat))
for(s in 1:Nsim)
  post.beta.sim[s,] = mvrnorm(1, betahat, post.sigma.2.sim[s]*Vbeta)
```

```{r}
# posterior interval
quantile(post.sigma.2.sim, c(0.025, 0.975))

apply(post.beta.sim, 2, quantile, c(0.025, 0.975))

confint(mod)

mean(post.beta.sim[,2] > 0)
```

## Prediction
```{r prediction}
# incomeGrowth on 2008 was 0.75
post.pred.y.sim = rnorm(Nsim, post.beta.sim[,1]+post.beta.sim[,2]*0.75,sqrt(post.sigma.2.sim))

quantile(post.pred.y.sim, c(0.025, 0.975))

predict(mod, data.frame(IncomeGrowth=0.75), interval="prediction")

# posterior predictive probability of 2008 incumbent victory
mean(post.pred.y.sim > 50)
```

## Model Checking
```{r diagnostic}
par(mfrow=c(2,2))
plot(mod)
```
## posterior-simulated standardized errors
```{r}
error.std.sim = matrix(NA, Nsim, nrow(bp))
for(s in 1:Nsim)
  error.std.sim[s,] = (bp$IncumbentPct - X %*% cbind(post.beta.sim[s,])) / sqrt(post.sigma.2.sim[s])

# rnorm can be used as it is standardized and independent
ref.std.normal = matrix(rnorm(Nsim*nrow(bp)), Nsim, nrow(bp))
```

## Test quantitiy
Checking for outliers
```{r}
max.t.rep = apply(abs(ref.std.normal),1, max)
max.t.sim = apply(abs(error.std.sim), 1, max)
mean(max.t.rep >= max.t.sim)
```



