---
title: "week13"
author: "kwon"
date: "2018년 11월 24일"
output: html_document
---

# Hierarchical Normal Regression
## Model
Using flint data, build
$$ y_{ij} | \beta^d, \beta^h, \sigma_y^2 \sim indep. N(\beta_j^d + \beta_i^h, \sigma_y^2) $$
$$ \beta_i^h | \sigma_h^2 \sim iid N (0, \sigma_h^2) $$
where, $\beta_i^h = $ household i effect(random), $\beta_j^d = $ draw j effect(fixed), \n
$\sigma_h^2 = $ variance between households, $\sigma_y^2 = $ measurement variance(within households) \n

Expect mean lead levels to fall as flushing time increases. \n

### priors
Noninformative
$$ p(\sigma_y^2) \propto (\sigma_y^2)^{-1}$$
$$ p(\sigma_h^2) \propto (\sigma_h^2)^{-1/2}$$

$$ p(\beta_1^d, \beta_2^d, \beta_3^d) \propto 1$$

```{r setup}
```

```{r read}
flint= read.table("flint-data-simple.txt", header=T, sep="\t")
head(flint)
```

## Modeling
```{r init}
# data prep for JAGS
d1 = list(loglead = log(flint[,c("FirstDraw", "After45Sec", "After2Min")]),
          betadraw0 = c(0,0,0),
          Sigmabetadrawinv = rbind(c(0.0001, 0, 0),
                                   c(0, 0.0001, 0),
                                   c(0, 0, 0.0001)))

# init 4 chains
inits1 = list(list(betadraw=c(100, 100, 100),
                   sigmasqyinv=0.0001, sigmahouse=100),
              list(betadraw= c(-100, -100, 100),
                   sigmasqyinv=1000, sigmahouse=0.01),
              list(betadraw=c(-100, 100, -100),
                   sigmaqyinv =0.0001, sigmahouse=0.01),
              list(betadraw=c(100, -100, -100),
                   sigmasqyinv = 1000, sigmahouse=100))
```






