---
title: "abm week 2"
author: "kwon"
date: "2018년 9월 7일"
output: html_document
---
## Flint data
### Read data
```{r}
Flintdata = read.csv("Flintdata.csv", row.names = 1)
head(Flintdata)
```

### Visualize
```{r}
hist(Flintdata$FirstDraw)
abline(v=15, col='red')
```

### Skewness
```{r}
summary(Flintdata$FirstDraw)
summary(log(Flintdata$FirstDraw))
hist(log(Flintdata$FirstDraw))
abline(v=log(15), col='red')
```

## Sample statistic
```{r}
(n = nrow(Flintdata))
(ybar = mean(log(Flintdata$FirstDraw)))
(s.2 = var(log(Flintdata$FirstDraw)))
```

## Posterior
```{r}
sigma.2 = s.2
mu0 = log(3)
tau.2.0 = sigma.2

# posterior mean
(mun = (mu0/tau.2.0 + n*ybar/sigma.2) / (1/tau.2.0 +n/sigma.2))

# posterior variance
(tau.2.n = 1 / (1/tau.2.0 + n/sigma.2))
```

## Plot posterior
```{r}
# posterior density
curve(dnorm(x, mun, sqrt(tau.2.n)), -1, 5, n=1000, ylab="Density")
# prior density
curve(dnorm(x, mu0, sqrt(tau.2.0)), -1, 5, add=TRUE, lty=2)
```

## Posterior interval
```{r}
(pci = mun+c(1, -1)*1.96*sqrt(tau.2.n))

# original scale
exp(pci)
```

```{r}
n = 200
y_mean = 2172
mu0 = 1875
sigma0 = 160
sigma1= 200

mun = ((1/sigma0^2)*mu0+(n/sigma1^2)*y_mean)/(1/sigma0^2 +n/sigma1^2)
sigman = 1/(1/sigma0^2 + n/sigma1^2)
mun
sqrt(sigman)
1/sigman
mun-1.96*sqrt(sigman)
mun+1.96*sqrt(sigman)
```

```{r}
theta = seq(0, 100, 0.1)
plot(theta, 1/theta^2, type="l")

```

# Non-informative prior analysis
```{r}
# Flint data
post.sigma.2.sim = (n-1)*s.2 / rchisq(1000, n-1)
post.mu.sim = rnorm(1000, ybar, sqrt(post.sigma.2.sim/n))
quantile(post.mu.sim, c(0.025, 0.975))
quantile(post.sigma.2.sim, c(0.025, 0.975))

# simualate from the posterior predictive distribution
post.pred.sim = rnorm(1000, post.mu.sim, sqrt(post.sigma.2.sim))

hist(post.pred.sim)
abline(v=log(15), col="red")
```





